services:
  controld-dashboard:
    image: ghcr.io/greg-hass/controld-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controld-dashboard
    ports:
      - "3173:80"
    restart: unless-stopped
    environment:
      TZ: Europe/London
      SCHEDULER_DATA_DIR: /data
    volumes:
      - controld-dashboard-data:/data

volumes:
  controld-dashboard-data:
